BridJ: updated native build scripts to run them from Maven and checkout + patch dyncall

diff --git a/libraries/Runtime/BridJ/BuildNative b/libraries/Runtime/BridJ/BuildNative
--- a/libraries/Runtime/BridJ/BuildNative
+++ b/libraries/Runtime/BridJ/BuildNative
@@ -1,32 +1,29 @@
 #!/bin/bash
 
-CLASSES="
-org.bridj.JNI
-org.bridj.BridJ
-org.bridj.Pointer
-org.bridj.Platform
-org.bridj.objc.ObjCJNI
-"
-
-if [[ "$@" != "clean" && "$@" != "fast" ]] ; then
-	# Generate native sources from Velocity templates
-	#mvn generate-sources -o
-	mvn compile -o
-	
-	# Generate JNI headers
-	javah -d src/main/cpp/bridj -classpath target/classes $CLASSES ;
+if [[ ! -d dyncall ]]
+then
+	admin/checkout_and_patch_dyncall.sh dyncall src/main/cpp/bridj/dyncall.diff || ( echo "Failed to checkout and patch dyncall" && exit 1 )
 fi
-	
+
+if [[ -z "$TARGETS" ]] ; then
+	if [[ -d /Applications ]] ; then
+		TARGETS="default ios android" ;
+	else
+		TARGETS="default" ;
+	fi ;
+fi
 
 cd src/main/cpp/bridj
 
-if [[ "$DEBUG" == "1" ]] ; then
-	BUILD_CONFIG=debug ./Make.sh $@ || exit 1 ;
-else 
-	if [[ "$@" == "fast" ]] ; then
-		./Make.sh || exit 1 ;
-	else
-		./Make.sh $@ || exit 1 ;
+for TARGET in $TARGETS ; do
+	if [[ "$DEBUG" == "1" ]] ; then
+		TARGET=$TARGET BUILD_CONFIG=debug ./Make.sh $@ || exit 1 ;
+	else 
+		if [[ "$@" == "fast" ]] ; then
+			TARGET=$TARGET ./Make.sh || exit 1 ;
+		else
+			TARGET=$TARGET ./Make.sh $@ || exit 1 ;
+		fi ;
 	fi ;
-fi
+done
 
